"""
Django settings for chron_track project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

from decouple import Csv, config

from chron_track import utils

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

SECRET_KEY = config("SECRET_KEY")
DEBUG = config("DEBUG", default=False, cast=bool)
ALLOWED_HOSTS = config("ALLOWED_HOSTS", default="", cast=Csv())
MODE = utils.determine_mode()
print(f"Mode found: {MODE}")

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "races",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "chron_track.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "chron_track.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Europe/Paris"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"


# ============== Testing Mode ==============
# Optimized SQLite configuration for fast parallel test execution

if MODE == "testing":
    import atexit
    import os
    import tempfile

    # Use a temporary file database instead of :memory: for tests
    # This allows test client connections to share the same database
    # :memory: creates a separate database for each connection!
    test_db_file = tempfile.NamedTemporaryFile(
        mode="w", suffix=".db", delete=False, prefix="test_chron_track_"
    )
    TEST_DB_NAME = test_db_file.name
    test_db_file.close()

    # Cleanup the temporary database file on exit
    def cleanup_test_db():
        try:
            if os.path.exists(TEST_DB_NAME):
                os.unlink(TEST_DB_NAME)
        except Exception:
            pass

    atexit.register(cleanup_test_db)

    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": TEST_DB_NAME,
            "OPTIONS": {
                "timeout": 30,
                "check_same_thread": False,
            },
            "ATOMIC_REQUESTS": False,
            "CONN_MAX_AGE": 0,
            "TEST": {
                "NAME": TEST_DB_NAME,
            },
        }
    }

    # SQLite optimization for concurrent access in tests
    from django.db.backends.signals import connection_created

    def configure_sqlite(sender, connection, **kwargs):
        """Configure SQLite for better concurrency in tests."""
        if connection.vendor == "sqlite":
            cursor = connection.cursor()
            cursor.execute("PRAGMA busy_timeout = 30000")
            cursor.execute("PRAGMA synchronous = NORMAL")
            cursor.execute("PRAGMA mmap_size = 268435456")  # 256MB

    connection_created.connect(configure_sqlite)

    # Faster password hashing for tests
    PASSWORD_HASHERS = [
        "django.contrib.auth.hashers.MD5PasswordHasher",
    ]

    # WhiteNoise's manifest storage requires collectstatic; fall back to the
    # plain static storage so tests don't crash on missing manifest entries.
    STORAGES = {
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }
