# Generated by Django 6.0.4 on 2026-05-10 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("fit", "Fit"),
                            ("gpx", "Gpx"),
                            ("tcx", "Tcx"),
                            ("strava_api", "Strava Api"),
                            ("garmin_api", "Garmin Api"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "sport_type",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("trail", "Trail"),
                            ("track", "Track"),
                            ("treadmill", "Treadmill"),
                        ],
                        default="running",
                        max_length=25,
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("duration", models.DurationField()),
                (
                    "distance",
                    models.DecimalField(
                        decimal_places=2, help_text="Distance in meters", max_digits=10
                    ),
                ),
                (
                    "elevation_gain",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="In meters",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "elevation_loss",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="In meters",
                        max_digits=8,
                        null=True,
                    ),
                ),
                ("avg_hr", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("max_hr", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "avg_cadence",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("calories", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Activity",
                "verbose_name_plural": "Activities",
                "ordering": ["-start_time"],
            },
        ),
        migrations.CreateModel(
            name="ActivityLap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lap_number", models.PositiveSmallIntegerField()),
                (
                    "distance",
                    models.DecimalField(
                        decimal_places=2, help_text="In meters", max_digits=10
                    ),
                ),
                ("duration", models.DurationField()),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("avg_hr", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("max_hr", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "avg_cadence",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "elevation_gain",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("calories", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="laps",
                        to="activity.activity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Activity Lap",
                "verbose_name_plural": "Activity Laps",
                "ordering": ["activity", "lap_number"],
            },
        ),
        migrations.AddConstraint(
            model_name="activity",
            constraint=models.UniqueConstraint(
                fields=("user", "start_time"), name="unique_user_start_time"
            ),
        ),
        migrations.AddConstraint(
            model_name="activitylap",
            constraint=models.UniqueConstraint(
                fields=("activity", "lap_number"), name="unique_activity_lap_number"
            ),
        ),
    ]
