# Generated by Django 6.0.4 on 2026-04-19 19:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Race",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the race",
                        max_length=255,
                        verbose_name="Name",
                    ),
                ),
                (
                    "edition",
                    models.CharField(
                        blank=True,
                        default=None,
                        help_text="Edition of the race",
                        max_length=255,
                        null=True,
                        verbose_name="Edition",
                    ),
                ),
                (
                    "date",
                    models.DateField(help_text="Date of the race", verbose_name="Date"),
                ),
                (
                    "distance",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Distance of the race (in kilometers)",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Distance",
                    ),
                ),
                (
                    "elevation_gain",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=None,
                        help_text="Elevation gain of the race (in meters)",
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Elevation gain",
                    ),
                ),
                (
                    "time",
                    models.DurationField(
                        help_text="Time of the race (in seconds)",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Time",
                    ),
                ),
                (
                    "speed",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Speed of the race (in kilometers per hour)",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Speed",
                    ),
                ),
                (
                    "pace",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Pace of the race (in minutes per kilometer)",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Pace",
                    ),
                ),
                (
                    "strava_url",
                    models.URLField(
                        blank=True,
                        help_text="URL of the race on Strava",
                        null=True,
                        verbose_name="Strava URL",
                    ),
                ),
                (
                    "results_url",
                    models.URLField(
                        blank=True,
                        help_text="URL of the race results",
                        null=True,
                        verbose_name="Results URL",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        default=None,
                        help_text="Location of the race",
                        max_length=255,
                        null=True,
                        verbose_name="Location",
                    ),
                ),
                (
                    "number_of_participants",
                    models.IntegerField(
                        blank=True,
                        default=None,
                        help_text="Number of participants in the race",
                        null=True,
                        verbose_name="Number of participants",
                    ),
                ),
                (
                    "global_ranking",
                    models.IntegerField(
                        blank=True,
                        default=None,
                        help_text="Global ranking of the race",
                        null=True,
                        verbose_name="Global ranking",
                    ),
                ),
                (
                    "category_ranking",
                    models.IntegerField(
                        blank=True,
                        default=None,
                        help_text="Category ranking of the race",
                        null=True,
                        verbose_name="Category ranking",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="races",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Race",
                "verbose_name_plural": "Races",
                "ordering": ["-date"],
            },
        ),
    ]
