# Generated by Django 6.0.4 on 2026-04-19 19:42

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("races", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="race",
            name="pace",
            field=models.DecimalField(
                decimal_places=2,
                editable=False,
                help_text="Pace of the race (in min/km)",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Pace",
            ),
        ),
        migrations.AlterField(
            model_name="race",
            name="speed",
            field=models.DecimalField(
                decimal_places=2,
                editable=False,
                help_text="Speed of the race (in km/h)",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Speed",
            ),
        ),
        migrations.AlterField(
            model_name="race",
            name="time",
            field=models.DurationField(
                help_text="Time of the race",
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Time",
            ),
        ),
        migrations.AddConstraint(
            model_name="race",
            constraint=models.CheckConstraint(
                condition=models.Q(("speed__gte", 0)), name="race_speed_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="race",
            constraint=models.CheckConstraint(
                condition=models.Q(("pace__gte", 0)), name="race_pace_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="race",
            constraint=models.CheckConstraint(
                condition=models.Q(("distance__gte", 0)), name="race_distance_positive"
            ),
        ),
    ]
