# Generated by Django 6.0.4 on 2026-04-19 19:48

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("races", "0002_alter_race_pace_alter_race_speed_alter_race_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="race",
            name="time",
            field=models.DurationField(
                help_text="Time of the race",
                validators=[
                    django.core.validators.MinValueValidator(datetime.timedelta(0))
                ],
                verbose_name="Time",
            ),
        ),
    ]
