name: CI Workflow

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.12

      - name: Install UV
        run: |
          python -m pip install --upgrade pip
          pip install uv

      - name: Run linting
        run: |
          uvx ruff check
          uvx flake8 .
          uvx black . --check
          uvx isort .
          uvx mypy src/

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.12

      - name: Install UV
        run: |
          python -m pip install --upgrade pip
          pip install uv

      - name: Install dependencies
        run: uv sync

      - name: Run tests with coverage
        run: |
          uv run coverage run -m pytest tests/
          uv run coverage report --fail-under=80
          uv run coverage xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          file: ./coverage.xml